# enable cors
quarkus.http.cors=true

quarkus.http.cors.origins=http://localhost:3000

quarkus.http.cors.methods=GET, POST, PUT, OPTIONS, PATCH

quarkus.http.cors.headers=authorization, headers, content-type